export const GET_CARGO_PROPOSALS = 'proposals/GET_CARGO_PROPOSALS';
// export const GET_TRANSPORT_PROPOSALS = 'proposals/GET_TRANSPORT_PROPOSALS';
export const SET_SELECT_ALL_PROPOSALS = 'proposals/SET_SELECT_ALL_PROPOSALS';
export const SET_SORTED_BY = 'proposals/SET_SORTED_BY';
export const SET_SORTED_DIRECTION = 'proposals/SET_SORTED_DIRECTION';
export const SET_SELECTED_LENGTH = 'proposals/SET_SELECTED_LENGTH';